import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { SupabaseProvider } from "@/components/SupabaseProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body>
    <SupabaseProvider> {/* ✅ Wrap entire app */}
          <Navbar />
          {children}
        </SupabaseProvider>
      </body>
    </html>
  );
}
